# Generated by Django 5.1.2 on 2024-11-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('not_available', 'Not Available'), ('way_to_pickup', 'Way to Pickup'), ('reached_pickup', 'Reached Pickup'), ('way_to_dropoff', 'Way to Dropoff'), ('on_ride', 'On Ride')], default='available', max_length=20),
        ),
    ]
