# Generated by Django 5.1.2 on 2024-11-07 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0003_tips'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('earning', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('outstanding', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
    ]
