# Generated by Django 5.1.2 on 2024-11-07 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0004_adminearning'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminearning',
            old_name='date',
            new_name='datetime',
        ),
    ]
